Feature/solr search implementation
robert-arias/news-website pull request #1
Opened 2021-02-18 17:33 UTC by robert-arias

# Solr implementation and related content view more fix

## Jira issue:

- None.

## How to test

- [ ] Search with solr.
- [ ] Open a news article, go to the related news block on the bottom and click on "Ver más".

2021-02-18 19:41 UTC, rigoucr commented
Hey Robert looking it your PR  I noticed that you forgot to add which commands did I needed to replicated your functionality in my local env. We always add the commands that the reviewer will require to setup the env , in this case the required ones were: `composer install && chirripo drush -- cim -y && chirripo drush -- cr`

When I tried to setup your branch in my local env, the `chirripo drush cim -y` command didn't work as expected:
```
 // Import the listed configuration changes?: yes.

 [error]  Drupal\Core\Config\ConfigImporterException: There were errors validating the config synchronization.
Unable to install the <em class="placeholder">search_api_autocomplete</em> module since it does not exist. in Drupal\Core\Config\ConfigImporter->validate() (line 755 of /var/www/html/web/core/lib/Drupal/Core/Config/ConfigImporter.php).

In ConfigImportCommands.php line 357:

  The import failed due to the following reasons:
  Unable to install the <em class="placeholder">search_api_autocomplete</em> module since it does not exist.
```

Seems like you forgot to add the module search_api_autocomplete to the composer.json

2021-02-18 19:50 UTC, robert-arias commented
Thank you for the feedback! Yes, I completely forgot to add the required commands for a smooth installation on your local dev; won't happen again!

About the error: I don't know why that error is being triggered, because the module is in the composer.json [here](https://github.com/robert-arias/news-website/blob/3b682fc79d19ebf707fed788e68b1f31bfb11224/composer.json#L58).

2021-02-22 22:21 UTC, robert-arias commented
The installation error has been fixed!

2021-02-22 22:51 UTC, rigoucr requested changes
almost there

2021-02-22 22:51 UTC, rigoucr commented on config/sync/core.extension.yml
> +  devel: 0
This module belongs only to the dev config context
```suggestion

```

2021-02-22 22:51 UTC, rigoucr commented on config/sync/core.extension.yml
> +  stage_file_proxy: 0
This module belongs only to the dev config context
```suggestion

```

2021-02-22 22:51 UTC, rigoucr commented on config/sync/core.extension.yml
> +  views_ui: 0
This module belongs only to the dev config context
```suggestion

```

2021-02-22 22:57 UTC, rigoucr approved these changes
Ship it :shipit:  !! thx!!!

2021-02-22 22:58 UTC, merged